namespace BTCPayServer.Plugins.Terminal.Services;

/// <summary>
/// Builds the Docker Compose fragment that adds litd to a btcpayserver-docker deployment, and the
/// host commands an operator runs to add, remove or wipe it.
/// </summary>
/// <remarks>
/// <para>
/// The commands are meant to be pasted into a root shell on the host. BTCPay Server cannot run them
/// itself: since 2.4.4 a plugin's only channel to the host is <c>btcpay-host</c>, whose host-side
/// script accepts a fixed whitelist (<c>env help changedomain update clean restart</c>) and has no
/// fragment command. Everything else this plugin does - status, sessions, logs - needs no host
/// access at all, so this is the one step an operator performs by hand.
/// </para>
/// <para>
/// The generated file is a <c>.custom.yml</c> fragment, which btcpayserver-docker gitignores inside
/// its own fragment directory; that is what keeps it in place across <c>btcpay-update.sh</c>.
/// </para>
/// </remarks>
public static class LitdFragment
{
    /// <summary>
    /// litd release run by the generated fragment.
    /// </summary>
    /// <remarks>
    /// btcpayserver-docker pins the <c>-path-prefix</c> rebuild of the same release, which exists only
    /// to serve the web UI's assets under <c>/lit/</c>. With <c>--disableui</c> there are no assets to
    /// serve, so the plain upstream Lightning Labs image is the right one here.
    /// Bump in step with btcpayserver-docker's own pin; see README.md.
    /// </remarks>
    public const string Image = "lightninglabs/lightning-terminal:v0.17.5-alpha";

    /// <summary>Path of the generated fragment on the host, relative to the deployment's base directory.</summary>
    public const string RelativePath =
        $"btcpayserver-docker/docker-compose-generator/docker-fragments/{TerminalOptions.FragmentName}.yml";

    /// <summary>
    /// The fragment's YAML. <c>${NBITCOIN_NETWORK}</c> is left for Compose to expand at run time,
    /// exactly as the upstream fragment leaves it, so the install snippet must quote its heredoc.
    /// </summary>
    public static string Yaml =>
        $$"""
        # {{TerminalOptions.FragmentName}}.yml
        #
        # Generated by the BTCPay Server "Lightning Terminal" plugin (terminal-btcpay).
        # This is btcpayserver-docker's own {{TerminalOptions.UpstreamFragmentName}}.yml with three changes:
        #
        #  1. litd runs with --disableui. With no web UI there is no UI password to generate, keep in
        #     secrets/lit_password or rotate, so that secret is gone. Manage the node from
        #     Server Settings > Lightning Terminal, which pairs Terminal on the web over LNC.
        #
        #  2. No required-routes. Upstream publishes /lit/ and the lnrpc./looprpc./poolrpc./litrpc.
        #     gRPC-web endpoints on the public BTCPay hostname in order to serve that UI. With the UI
        #     off there is nothing to publish, and litd stays reachable only inside the Docker network.
        #
        #  3. litd's data directory is mounted read-only into the BTCPay Server container. That mount is
        #     how the plugin reads litd's TLS certificate, macaroon and log file, which is what lets it
        #     report status and mint LNC sessions without any access to this host.
        #
        # The plugin regenerates this file on every install. Change it from the plugin, not by hand.

        services:
          btcpayserver:
            volumes:
              - "{{TerminalOptions.DataVolumeName}}:/lit:ro"
          lnd_bitcoin:
            environment:
              LND_EXTRA_ARGS: |
                rpcmiddleware.enable=true
          lnd_lit:
            image: "{{Image}}"
            restart: unless-stopped
            environment:
              LIT_AUTO_MIGRATE_TO_SQL: "true"
            expose:
              - "8080"
            volumes:
              - "{{TerminalOptions.DataVolumeName}}:/root/.lit"
              - "lnd_bitcoin_datadir:/data/lnd:ro"
              - "bitcoin_datadir:/deps/.bitcoin:ro"
            links:
              - bitcoind
              - lnd_bitcoin
            command:
              - "--disableui"
              - "--insecure-httplisten=0.0.0.0:8080"
              - "--network=${NBITCOIN_NETWORK}"
              - "--lnd-mode=remote"
              - "--remote.lnd.rpcserver=lnd_bitcoin:10009"
              - "--remote.lnd.macaroonpath=/data/lnd/admin.macaroon"
              - "--remote.lnd.tlscertpath=/data/lnd/tls.cert"
              - "--faraday.connect_bitcoin"
              - "--faraday.bitcoin.host=bitcoind:43782"
              - "--faraday.bitcoin.user=lnd"
              - "--faraday.bitcoin.passwordfile=/deps/.bitcoin/RPCUsers/lnd"

        volumes:
          {{TerminalOptions.DataVolumeName}}:

        required:
          - "bitcoin-lnd"
        """;

    /// <summary>
    /// Writes the fragment and selects it. <c>btcpay-fragments add</c> regenerates the Compose file and
    /// brings the stack back up immediately, so BTCPay Server itself restarts partway through.
    /// </summary>
    /// <remarks>
    /// Every command here runs in a <c>( set -eu )</c> subshell. These are pasted into a root shell, so
    /// an unset <c>BTCPAY_BASE_DIRECTORY</c> - on a host that is not a btcpayserver-docker deployment -
    /// has to stop the block rather than resolve to a path under <c>/</c>. A subshell also means a
    /// failure never closes the operator's session the way a bare <c>exit</c> would.
    /// </remarks>
    public static string InstallCommand =>
        $"""
        (
        set -eu
        . /etc/profile.d/btcpay-env.sh
        cat > "$BTCPAY_BASE_DIRECTORY/{RelativePath}" <<'LITD_FRAGMENT'
        {Yaml}
        LITD_FRAGMENT
        btcpay-fragments add {TerminalOptions.FragmentName}
        )
        """;

    /// <summary>
    /// Replaces btcpayserver-docker's own Lightning Terminal fragment with this plugin's headless one,
    /// keeping litd's data volume and so the node's existing accounts, sessions and history.
    /// </summary>
    /// <remarks>
    /// Two <c>btcpay-fragments</c> calls, because each one regenerates and restarts the stack the moment
    /// it runs and there is no combined remove-and-add. litd is therefore down between them.
    /// </remarks>
    public static string SwitchCommand =>
        $"""
        (
        set -eu
        . /etc/profile.d/btcpay-env.sh
        cat > "$BTCPAY_BASE_DIRECTORY/{RelativePath}" <<'LITD_FRAGMENT'
        {Yaml}
        LITD_FRAGMENT
        btcpay-fragments remove {TerminalOptions.UpstreamFragmentName}
        btcpay-fragments add {TerminalOptions.FragmentName}
        )
        """;

    /// <summary>
    /// Deselects the fragment and regenerates the stack without litd. litd's data volume is
    /// untouched: nothing here removes a named Compose volume, so the macaroon, accounts, sessions
    /// and Loop/Pool/Faraday records all survive, and a later re-install picks them straight back up.
    /// </summary>
    public static string UninstallCommand =>
        $"""
        (
        set -eu
        . /etc/profile.d/btcpay-env.sh
        btcpay-fragments remove {TerminalOptions.FragmentName}
        )
        """;

    /// <summary>
    /// Removes litd and then destroys its data volume. Irreversible: the macaroon, every LNC session,
    /// every Loop/Pool/Faraday record and litd's own database go with it. LND's own data is in a
    /// separate volume and is not touched.
    /// </summary>
    /// <remarks>
    /// Both the generated fragment and btcpayserver-docker's own are deselected, because either of them
    /// keeps a container attached to the volume, and each is removed only if it is actually selected -
    /// <c>btcpay-fragments</c> rebuilds and restarts the whole stack on every call, selected or not.
    /// </remarks>
    public static string WipeCommand =>
        $$"""
        (
        set -eu
        . /etc/profile.d/btcpay-env.sh
        for fragment in {{TerminalOptions.FragmentName}} {{TerminalOptions.UpstreamFragmentName}}; do
            if btcpay-fragments show | jq -e --arg f "$fragment" '.additionalFragments | index($f) != null' > /dev/null; then
                btcpay-fragments remove "$fragment"
            fi
        done
        rm -f "$BTCPAY_BASE_DIRECTORY/{{RelativePath}}"
        volume="$(docker volume ls -q | grep -E '(^|_){{TerminalOptions.DataVolumeName}}$' || true)"
        if [ -n "$volume" ]; then
            docker volume rm "$volume"
        else
            echo "No {{TerminalOptions.DataVolumeName}} volume found - nothing left to wipe."
        fi
        )
        """;
}
