using System.Text.Json;
using BTCPayServer.Plugins.LightningTerminal.Services;
using Xunit;

namespace BTCPayServer.Plugins.LightningTerminal.UnitTests;

/// <summary>
/// Checks the macaroon v2 encoder against vectors generated by gopkg.in/macaroon.v2 - the same library
/// lnd uses to bake and litd uses to narrow.
/// </summary>
/// <remarks>
/// Hand-rolled crypto on a credential is only defensible if it is checked against the reference
/// implementation, so every assertion here compares to bytes Go produced.
/// </remarks>
public class MacaroonTests
{
    private sealed record Vector(
        string Note, string RootKeyHex, string IdHex, string Location,
        // Go marshals a nil slice as null, and "no caveats at all" is a case worth keeping.
        string BeforeHex, string[]? Caveats, string AfterHex);

    private static readonly Vector[] Vectors =
        JsonSerializer.Deserialize<Vector[]>(
            File.ReadAllText("macaroon-vectors.json"),
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;

    public static TheoryData<string> VectorNotes()
    {
        var data = new TheoryData<string>();
        foreach (var vector in Vectors)
            data.Add(vector.Note);
        return data;
    }

    private static Vector ByNote(string note) => Vectors.Single(vector => vector.Note == note);

    [Fact]
    public void TheVectorsLoaded()
    {
        // Every test below is vacuous if the file went missing from the output directory.
        Assert.NotEmpty(Vectors);
    }

    [Theory]
    [MemberData(nameof(VectorNotes))]
    public void AddingTheCaveatsProducesGosBytesExactly(string note)
    {
        var vector = ByNote(note);
        var macaroon = Macaroon.FromHex(vector.BeforeHex);

        foreach (var caveat in vector.Caveats ?? [])
            macaroon.AddFirstPartyCaveat(caveat);

        Assert.Equal(vector.AfterHex, macaroon.ToHex());
    }

    [Theory]
    [MemberData(nameof(VectorNotes))]
    public void ParsingAndReserialisingChangesNothing(string note)
    {
        // The encoder has to be byte-exact before the signature means anything: a macaroon that
        // round-trips differently would verify against nothing.
        var vector = ByNote(note);

        Assert.Equal(vector.BeforeHex, Macaroon.FromHex(vector.BeforeHex).ToHex());
        Assert.Equal(vector.AfterHex, Macaroon.FromHex(vector.AfterHex).ToHex());
    }

    [Fact]
    public void AddingACaveatChangesTheSignature()
    {
        var vector = ByNote("no caveats at all");
        var macaroon = Macaroon.FromHex(vector.BeforeHex);

        macaroon.AddFirstPartyCaveat("lnd-custom account 0011223344556677");

        Assert.NotEqual(vector.BeforeHex, macaroon.ToHex());
    }

    [Theory]
    [InlineData("not hex at all")]
    [InlineData("")]
    [InlineData("0102")]                     // too short to hold anything
    [InlineData("0301036c6e6402016100000620")] // version 3
    public void MalformedInputIsRejectedRatherThanGuessedAt(string hex)
    {
        // A silently mangled macaroon would be handed out as a working credential and fail only when
        // someone tried to use it.
        Assert.ThrowsAny<FormatException>(() => Macaroon.FromHex(hex));
    }
}
